### PR TITLE
add reference urls in the demo presentation

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by viebel** [comment]
@timothypratley when you update `slides.adoc` on github, does it automatically update the [Live Example](https://timothypratley.github.io/asciidoctor-revealjs-klipse/slides.html)?

**Comment by timothypratley** [comment]
@viebel Not yet, but it is very easy to add via Travis. I will add this and some documentation on how it is achieved soon. For now, I'll manually deploy this. Thanks for the fixes! 👍

**Comment by timothypratley** [comment]
@viebel Just letting you know; I added automatic deployment

**Comment by viebel** [comment]
@timothypratley That's great!
I am also asking myself what is the best way to expose other languages that Klipse supports like: scheme, prolog, react, ruby etc...

If we add a klipse snippet for each language on the slides, it will increase significantly the load time because all the interpreters will be downloaded.

Do you have an idea?

**Comment by timothypratley** [comment]
@viebel I have not tried that but am interested as well. I can try that out this weekend. My initial thoughts are that often with a presentation it is O.K. to have slow startup time, or maybe there is a way we can stagger the loading so the first slide is ready earlier than the later slides. Also I have noticed if I have lots and lots of snippets I need to break up my page. Maybe there is a way to selectively load the snippets of interest only. RevealJS seems to have a concept of current slide + neighboring slides... so there might be a way to plug into that.

**Pull request merged**
